import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/nav-bar";
import Logo from "@/components/logo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased xl:w-7xl lg:w-6xl w-full min-h-screen  mx-auto flex`}
      >
        <div className="fixed md:top-0 bottom-0 w-full xl:w-52 lg:w-32 md:w-10 md:h-full h-10 flex md:flex-col flex-row gap-1">
          <Logo />
          <NavBar />
        </div>
        <main className="xl:ml-52 lg:ml-32 md:ml-10 p-6 flex-1 ">
          {children}
        </main>
      </body>
    </html>
  );
}
